export type WNBADailyGame = {
  id?: number | null;
  source_event_id?: string | null;
  game_date: string;
  scheduled_at?: string | null;
  scheduled_at_arg?: string | null;
  season?: string | null;
  season_type?: string | null;
  status_state?: string | null;
  status_type?: string | null;
  status_name?: string | null;
  status_detail?: string | null;
  away_team_abbr: string;
  away_team_name: string;
  away_team_logo?: string | null;
  away_score?: number | null;
  home_team_abbr: string;
  home_team_name: string;
  home_team_logo?: string | null;
  home_score?: number | null;
  home_win_prob?: number | null;
  away_win_prob?: number | null;
  home_win_pct?: number | null;
  away_win_pct?: number | null;
  h2h_home_wins?: number | null;
  h2h_away_wins?: number | null;
  h2h_total?: number | null;
  model_note?: string | null;
  updated_at?: string | null;
};

export type WNBATeamRow = {
  team_id: number;
  team_abbr: string | null;
  team_name: string | null;
  season: string | null;
  season_type: string | null;
  gp: number | null;
  w: number | null;
  l: number | null;
  w_pct: number | null;
  pts: number | null;
  reb: number | null;
  ast: number | null;
  plus_minus: number | null;
};

export type WNBAPlayerRow = {
  player_id: number;
  player_name: string | null;
  team_id: number | null;
  team_abbr: string | null;
  jersey?: string | null;
  position?: string | null;
  height?: string | null;
  country?: string | null;
  school?: string | null;
  season?: string | null;
  season_type?: string | null;
  gp?: number | null;
  min?: number | null;
  pts?: number | null;
  reb?: number | null;
  ast?: number | null;
  stl?: number | null;
  blk?: number | null;
  turnovers?: number | null;
  fg_pct?: number | null;
  fg3_pct?: number | null;
  ft_pct?: number | null;
  ts_pct?: number | null;
  usg_pct?: number | null;
  pie?: number | null;
};

export type WNBALogRow = {
  game_id: string;
  game_date: string;
  player_id: number;
  player_name: string;
  team_id?: number | null;
  team_abbreviation: string;
  opponent_abbr: string;
  home_away: string;
  wl: string | null;
  minutes?: string | number | null;
  min?: string | number | null;
  pts: number | null;
  reb: number | null;
  ast: number | null;
  stl: number | null;
  blk: number | null;
  turnovers: number | null;
  pf?: number | null;
  fgm: number | null;
  fga: number | null;
  fg_pct: number | null;
  fg3m: number | null;
  fg3a: number | null;
  fg3_pct: number | null;
  ftm: number | null;
  fta: number | null;
  ft_pct: number | null;
  plus_minus: number | null;
  ts_pct?: number | null;
  usg_pct?: number | null;
  pie?: number | null;
};

export type WNBAPreparedLog = WNBALogRow & {
  matchup: string;
  game_date_safe: string;
  minutes_value: number;
  pra: number;
  pts_reb: number;
  pts_ast: number;
  reb_ast: number;
  stl_blk: number;
};
